#!/usr/bin/env php
<?php

/*
 * This file is part of the coole-php/skeleton.
 *
 * (c) guanguans <ityaozm@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled.
 */

require __DIR__.'/vendor/autoload.php';

use Guanguans\Coole\App;

$app = App::getInstance()->make('console');

$app->run();
