#!/usr/bin/env php
<?php

/*
 * This file is part of the coole-php/skeleton.
 *
 * (c) guanguans <ityaozm@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled.
 */

! defined('BASE_PATH') && define('BASE_PATH', __DIR__);

require BASE_PATH.'/vendor/autoload.php';

app('console')->run();
